---
# RabbitMQ official install

- name: Install packages necessary to add rabbitmq's repository
  apt:
    name:
      - apt-transport-https
      - gnupg
    state: latest
    update_cache: true

- name: Add rabbitmq repo
  deb822_repository:
    name: rabbitmq
    types: deb
    uris:
      - "https://deb1.rabbitmq.com/rabbitmq-erlang/debian/{{ ansible_distribution_release }}"
      - "https://deb2.rabbitmq.com/rabbitmq-erlang/debian/{{ ansible_distribution_release }}"
      - "https://deb1.rabbitmq.com/rabbitmq-server/debian/{{ ansible_distribution_release }}"
      - "https://deb2.rabbitmq.com/rabbitmq-server/debian/{{ ansible_distribution_release }}"
    suites: "{{ ansible_distribution_release }}"
    components: main
    architectures: amd64
    signed_by: >-
      https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA

- name: Install rabbitmq-server
  apt:
    name: rabbitmq-server
    state: present
    update_cache: true

- name: Enable rabbitmq-server to survive reboot
  service:
    name: rabbitmq-server
    enabled: true
