---
# Debian install
- name: Install rabbitmq on Debian
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install rabbitmq on RPM Distros
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
