---
- name: Active the federation plugin
  community.rabbitmq.rabbitmq_plugin:
    names: rabbitmq_federation
    new_only: true
  register: federation_plugin

- name: Restart RabbitMQ to be able to setup federation
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted
  when: federation_plugin.changed

- name: Set the federation-upstream parameter
  community.rabbitmq.rabbitmq_parameter:
    component: federation-upstream
    name: "{{ item.name }}"
    vhost: "{{ item.vhost | default('/', false) }}"
    value: "{{ item.value }}"
  loop: "{{ rabbitmq_federation_configuration }}"

- name: Set the policy for the federation
  community.rabbitmq.rabbitmq_policy:
    name: "{{ item.name }}"
    vhost: "{{ item.vhost | default('/', false) }}"
    pattern: "{{ item.pattern }}"
    tags: "{{ item.tags }}"
  loop: "{{ rabbitmq_policy_configuration }}"

- name: Get the version of rabbitmq
  ansible.builtin.shell:
    cmd: |
      set -e -o pipefail
      rabbitmqctl status | awk '{print $NF}'
  args:
    executable: /bin/bash
  register: rabbitmq_version

# local-username is no longer required with 3.3.0
# http://www.rabbitmq.com/release-notes/README-3.3.0.txt
- name: Set the local username for the federation
  community.rabbitmq.rabbitmq_parameter:
    component: federation
    name: local-username
    value: "{{ item.local_username | default('guest', false') }}"
    vhost: "{{ item.vhost | default( '/', false) }}"
  loop: "{{ rabbitmq_federation_configuration }}"
  when: rabbitmq_version.stdout | version_compare('3.3.0', '<')
