---
- name: Enable plugins
  community.rabbitmq.rabbitmq_plugin:
    names: "{{ rabbitmq_plugins | join(',') }}"
    new_only: "{{ rabbitmq_new_only }}"
  notify: restart rabbitmq-server
  when: rabbitmq_plugins != []

- name: Get the list of active plugins to disable
  ansible.builtin.command:
    argv:
      - rabbitmq-plugins list
      - -e
      - -m
  register: result
  when: rabbitmq_plugins == []

- name: Disable plugins if none added in the configuration
  community.rabbitmq.rabbitmq_plugin:
    name: "{{ item }}"
    state: disabled
  notify: restart rabbitmq-server
  with_items: "{{ result.stdout_lines }}"
  when: rabbitmq_plugins == []
