---
- name: Get port 5672 on address 0.0.0.0
  ansible.builtin.shell: netstat -an | grep 0.0.0.0:5672.*LISTEN
  register: test_result
  ignore_errors: true

- name: Ensure RabbitMQ is listenning on tcp port
  ansible.builtin.assert:
    that:
      - test_result|failed

- name: Get port 5671 on address 0.0.0.0
  ansible.builtin.shell: netstat -an | grep 0.0.0.0:5671.*LISTEN
  register: test_result

- name: Ensure RabbitMQ is listenning on tls port
  ansible.builtin.assert:
    that:
      - test_result|success

- name: Get RabbitMQ virtual hosts
  ansible.builtin.shell: rabbitmqctl list_vhosts | grep sensu
  register: test_result

- name: Ensure the sensu vhost was added
  ansible.builtin.assert:
    that:
      - "{{ test_result.rc }} == 0"

- name: Get RabbitMQ users
- ansible.builtin.shell: rabbitmqctl list_users | grep sensu
  register: test_result

- name: Ensure the sensu user was added
  ansible.builtin.assert:
    that:
      - "{{ test_result.rc }} == 0"

- name: Get sensu's permissions
  ansible.builtin.shell: rabbitmqctl list_permissions -p sensu | grep ^sensu
  register: test_result

- name: Ensure the sensu user was added to the sensu vhost
  ansible.builtin.assert:
    that:
      - "{{ test_result.rc }} == 0"

- name: Get RabbitMQ plugins
  ansible.builtin.shell: rabbitmq-plugins list | grep 'rabbitmq_federation ' | grep '^\[E\]' | wc -l
  register: test_result

- name: Ensure federation plugin was installed
  ansible.builtin.assert:
    that:
      - "{{ test_result.stdout }} == 1"
  when: rabbitmq_federation == true

- name: Get federation-upstream parameter
- ansible.builtin.shell: rabbitmqctl list_parameters -p sensu | grep ^federation-upstream | grep test | wc -l
  register: test_result
- name: Ensure federation-upstream parameter set
  ansible.builtin.assert:
    that:
      - "{{ test_result.stdout }} == 1"

- name: Get federation policy's status
  ansible.builtin.shell: rabbitmqctl list_policies -p sensu | grep ^sensu | grep '{"federation-upstream-set":"all"}' | wc -l
  register: test_result

- name: Ensure federation policy set
  ansible.builtin.assert:
    that:
      - "{{ test_result.stdout }} == 1"
